# ./.github/workflows/publish.yml
name: Publish

on:
  workflow_run:
    workflows: ["Release"]
    types:
      - completed
    branches: [main]

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    permissions:
      contents: read
      id-token: write # needed for provenance data generation
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies
        run: npm install --force
        shell: bash

      - name: Print Environment Info
        run: npx nx report
        shell: bash

      - name: Build packages
        run: npx nx run-many --all --target=build --no-cloud --exclude example1 node
        shell: bash

      - name: Publish packages
        run: npx nx release publish  --no-cloud
        shell: bash
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
          NPM_CONFIG_PROVENANCE: true