name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/

      - name: Setup Git
        run: |
          git config user.name "Atikur(GitHub Action)"
          git config user.email "atikassam@outlook.com"

      - run: npm install

      - name: Create release branch
        id: create_branch
        shell: bash
        run: |
          BRANCH_NAME=release-$(date +'%Y%m%d%H%M%S')
          echo "branch_name=${BRANCH_NAME}" >> $GITHUB_ENV
          git checkout -b $BRANCH_NAME
          git push origin HEAD

      - name: Switch to release branch and run release
        shell: bash
        run: |
          git checkout ${{ env.branch_name }}
          npx nx release --skip-publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set last-release tag
        shell: bash
        run: |
          git tag -f last-release
          git push origin last-release --force

      - name: Create a Pull Request
        id: create_pr
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ env.branch_name }}
          base: main
          title: "Release: $(date +'%Y-%m-%d')"
          body: |
            This PR contains the changes for the latest release.
          draft: false

      - name: Merge the Pull Request
        uses: actions/github-script@v7
        with:
          script: |
            const prNumber = parseInt(process.env.PR_NUMBER);
            if (prNumber) {
              await github.pulls.merge({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: prNumber,
                merge_method: 'squash',
              });
            } else {
              console.log('No pull request to merge.');
            }
        env:
          PR_NUMBER: ${{ steps.create_pr.outputs.pull-request-number }}